USE [master]
GO

/****** Object:  Database [CarRentalDatabase]    Script Date: 7.03.2021 16:18:17 ******/
CREATE DATABASE [CarRentalDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CarRentalDatabase', FILENAME = N'C:\Users\ofaru\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\CarRentalDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CarRentalDatabase_log', FILENAME = N'C:\Users\ofaru\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\CarRentalDatabase.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CarRentalDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CarRentalDatabase] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [CarRentalDatabase] SET ANSI_NULLS ON 
GO

ALTER DATABASE [CarRentalDatabase] SET ANSI_PADDING ON 
GO

ALTER DATABASE [CarRentalDatabase] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [CarRentalDatabase] SET ARITHABORT ON 
GO

ALTER DATABASE [CarRentalDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CarRentalDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CarRentalDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CarRentalDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CarRentalDatabase] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [CarRentalDatabase] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [CarRentalDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CarRentalDatabase] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [CarRentalDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CarRentalDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CarRentalDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CarRentalDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CarRentalDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CarRentalDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CarRentalDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CarRentalDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CarRentalDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CarRentalDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [CarRentalDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [CarRentalDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CarRentalDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CarRentalDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CarRentalDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CarRentalDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CarRentalDatabase] SET QUERY_STORE = OFF
GO

USE [CarRentalDatabase]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CarRentalDatabase] SET  READ_WRITE 
GO

